### ISSUE TITLE
Hold and choose keyboard

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#101]

**Comment by PietroLiuzzo** [comment]
sind die nicht? 
hold ሀ --> "ሁ", "ሂ", "ሃ", "ሄ", "ህ", "ሆ", etc.
        a -->  u,   i,  ā,  e,   ǝ,     o

**Comment by AndreasEllwardt** [comment]
wu - wi - wa: - we - w - wo - irgendwas komisches Oromo o.ä.



Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
Diese Hinweis ist zu elliptisch für mich zu verstanden. Entschuldigung!
