### ISSUE TITLE
die Buttons "löschen" und "vorwärts" sind immer noch gefährlich nahe aneinander

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#102]

**Comment by PietroLiuzzo** [comment]
ich habe den Margin von 8 bis 20px erhöhet, ich hoffe es reicht für den Papierkorb. den vorwärts, meinst du die kleine Pfeile?

**Comment by PietroLiuzzo** [comment]
ich habe den link wo di Navigationspfeile sind an der text auch hinzugefügt und die Pfeile 20px entfernt

**Comment by AndreasEllwardt** [comment]
genau, die kleinen Pfeile!




Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
bitte issue schlissen
