### ISSUE TITLE
inconsistency in the visualization of the entries 

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/dillmann#104]
Some of those entries from Dillmann, to which new information (as different use or meaning of the word... ) from TraCES corpus are added, appear also within the list of "New Entries"; others appear only in the "List of Words" (Dillmann). See, e.g., the entries: ባሕር፡ and ማእከል፡.
In the case of ባሕር፡, when you open the entry from the list of "New Entries" by the first click, the two information from Dillmann and TraCES apper inverted  (first Traces, second Dillmann) and in a mixed order.

**Comment by PietroLiuzzo** [comment]
I have added the language and column to organize better the transformation results. would you like it exactly as in the normal view?

**Comment by vitagrazia81** [comment]
Thanks Pietro. To have added the language was a good idea. Maybe to have it in the normal view (with the indication of the languages not abbreviated) it would be even better. But it is only what I think. Maybe for the others it is not so needed. 
The other inconstistency I meant above is, for instance, that ባሕር፡ and ማእከል፡, both words already in Dillmann and now with a new information from Marrassini, are not viewable in the same way: the second appears only once and in the Latin list, the first in both. 
Then, another thing is: if you open a letter in the latin list, not for all  the words displayed the meanings  are visible. You can again compare, as an example, the words above.

**Comment by PietroLiuzzo** [comment]
the new entry list only contains the entries which are not in Dillmann, not those which have new content. I could add a similar view which lists all what as as source Traces, which would contain the second term. to ባሕር `<nd/>` was wrongly added

**Comment by PietroLiuzzo** [comment]
there was a problem with the latin list, which should be now solved, now the meanings of ባሕር are there

**Comment by PietroLiuzzo** [comment]
#115 #81 
I am closing this issue as now the list view have been merged and updated. The display difference remains. only if new terms or terms with a `sense[@source="#traces"]` will have the full entry display.
