### ISSUE TITLE
"Source of Sence" appearing marked wrongly as "Latin" instead "English", for some new entries .

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/dillmann#105]
When you view the content of some of the "New entries", the "Source of Sence" appears as "Latin" (Dillmann source) instead of "English" (TraCES source).  On the bottom "I" at the right side of the word "Latin", however, you read the information about TraCES.
See, e.g., the words: መንዝሕ, በጌ.

**Comment by PietroLiuzzo** [comment]
this is because of <Sla< which needs to be <Sen<.
