### ISSUE TITLE
In the transcription of the labiovelars the letter w appears not in superscript

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/dillmann#107]
In the transcription of some new entries, the ones already imported, the letter w of the labiovelars appears not in superscript. See, e.g., the word ጐጃም/ጐዣም፡.

**Comment by PietroLiuzzo** [comment]
@vitagrazia81 
I am not sure I get this right. I have looked at this one and entered the superscript w and it does not seam to have problems. http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Lbb2c7db04e1e4b20b1a3c5455846865b

if the normal w is entered it will not be marked as superscript automatically, you need to enter the correct ʷ character which is for your convenience in the keyboard.

**Comment by vitagrazia81** [comment]
Yes Pietro, you are right, thanks. But last time (last Friday) the keybord could not be opened  (for the entries to edit newly, it was openable). Then, I meant the entries which were written in word and only then imported in the tool. I think the tool just changed automatically a labiovelar letter into two normal and separeted letters. I wanted just to signal it.
