### ISSUE TITLE
columns

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/dillmann#111]
It would be very useful to have the possibility of knowing exactly where we are, in which column, when searching the (Dillmann) Lexicon: columns are marked in the text file and it should be possible to retrieve the infromation in a relatively easy way

from @abausi in main repo

**Comment by PietroLiuzzo** [comment]
At the moment columns indicated in the source file in txt are marked in the TEI file as `<cb/>` and take a corresponding id. they are visualized as in this example with a columns icon from fontawsome.
http://betamasaheft.aai.uni-hamburg.de/Dillmann/index.html?mode=none&q=fides&id=Ld81f28f1ff824eb6b56d068ed106c2d8
 
please let me know what should be changed. do I understand correctly that you would you like to know for each entry where you are?

**Comment by abausi** [comment]
yes, ponje would like to know, where we are, for those entries which are in Dillmann's Lexicon (in the narrow sense); I cannot see the columns icon: where is it exactly placed?

**Comment by PietroLiuzzo** [comment]
in the home page view there should be now a small badge with this indication. I have made this yellowish like the highlighting and applied the same classes to the column breaks in the text. please close issue if this is now ok.
