### ISSUE TITLE
Hinc meist ein Link aufs nächste Lemma!

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#114]
http://betamasaheft.aai.uni-hamburg.de/Dillmann/index.html?q=hinc&mode=none

**Comment by PietroLiuzzo** [comment]
when Hinc appears in the text, it will take a link to the next entry and also print the lemma. http://betamasaheft.aai.uni-hamburg.de/Dillmann/index.html?mode=none&q=hinc&id=Lcb52890bdbb2413a8d8f9a55f928e6da
