### ISSUE TITLE
Greek Words

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#123]
Searching for πεντηκοστή brings 0 results, meanwhile searching for πεντηκοστή brings 1 result.

**Comment by PietroLiuzzo** [comment]
I see no difference between the two. have you checked the codes used by each?

**Comment by PietroLiuzzo** [comment]
the first example ends with \u03ae (http://graphemica.com/%CE%AE)
the second example ends with \u1f75 (http://graphemica.com/%E1%BD%B5)
it sounds to me the first would be right, the second is what was in the source text (from ocr??). 
would it be a correct fix to substitute the first with the second?

**Comment by AndreasEllwardt** [comment]
The first one would be right indeed, it cam from Wikipedia. The second one came from the Dillmann text itself, so it would be correct to replace in the whole file u1f75 by u03ae.

**Comment by PietroLiuzzo** [comment]
1102 instances replaced
