### ISSUE TITLE
the information "root" must be inserted

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#125]
If I look, e.g. for ቅድሳት፡, I will get the correct result with the best match: the lemma ቅድሳት፡, but the gleichermaßen pertinent ቅዱስ፡, which has a plural form ቅድሳት፡ will be placed very far away. This could be solved by adding an information about the root and sorting according to that.

**Comment by PietroLiuzzo** [comment]
moved this to lexicon requirement

**Comment by PietroLiuzzo** [comment]
https://github.com/TraCES-Lexicon/lexicon/issues/12

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Dillmann/issues/142
