### ISSUE TITLE
s.v. ሰርገወ

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#126]
(coll. \*ar*سَرِجَ\* et \*ar*سَرَجَ\* I et II, \*syr*ܣܪܰܓ\* \*he*סְרַג\* al.): here, the Syriac comes before the Hebrew, as it should be, but here: (crebro per ሠ ) rad.quadril.; eam in Dillmann 1857 § 73 praefixo ሰ፡ causativo e ረገወ፡ ( vid. ረገፈ፡ ) formatam censui; nunc (cum Hupfeld exerc. Aeth. 29 ) ሰረገ፡ plectere , comere , ornare (coll. سَرِجَet سَرَجَI et II, ܣܪܰܓ סְרַגal.) statuere maluerim, it is the other way round.

**Comment by AndreasEllwardt** [comment]
By the way, the missing blanks  in (coll. سَرِجَ et سَرَجَ I et II, ܣܪܰܓ סְרַג al.) make it rather difficult to read and understand, could they perhaps been taken from the many superfluous ones as in (crebro per ሠ ) or ( vid. ረገፈ፡ )?

**Comment by PietroLiuzzo** [comment]
is this any better now?
http://betamasaheft.aai.uni-hamburg.de/Dillmann/index.html?mode=none&q=%E1%88%B0%E1%88%AD%E1%8C%88%E1%8B%88&id=L58708c282b6f46cba69a48e38be7792f
