### ISSUE TITLE
Kleinigkeit

### ISSUE THREAD

**Issue by wdickhut** [SChAth/dillmann#128]
http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Lc653a3fb32a94e309838d19d347713ff
Hier ist "5)" als Aufzählungspunkt fehlinterpretiert.

**Comment by PietroLiuzzo** [comment]
I have fixed this but please note that this is something rather easy to fix in the app. 
<5< and >5> need to be removed 
Matth. 5 needs to be correctly marked as reference *Matth.|5*
