### ISSUE TITLE
App is down again

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#132]

**Comment by PietroLiuzzo** [comment]
false, I am using it. you must be getting an error of some sort, please report it.

**Comment by AndreasEllwardt** [comment]
false alarm: it was so slow that I got the impression it was down

**Comment by AndreasEllwardt** [comment]
I had already to restart it several times, Wolfgang too.

**Comment by PietroLiuzzo** [comment]
I wonder how you restart it. you mean reloading the page?

**Comment by AndreasEllwardt** [comment]
not reloading the page, but clicking Lexicon again

**Comment by AndreasEllwardt** [comment]
it is very, very slow

**Comment by PietroLiuzzo** [comment]
I got the point, thanks.

**Comment by AndreasEllwardt** [comment]
Alessandro blames me for thinking to slowly, but I am faster than the app today
