### ISSUE TITLE
s.v. ደቂቅ

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#138]
wrong nesting

**Comment by PietroLiuzzo** [comment]
Thanks, there is no need to signal each of these wrongly nested entry as there is already an open issue generally about them. 
It is also possible to directly correct them as you find one, using the editor.
#76

**Comment by PietroLiuzzo** [comment]
I have intruduced II). Please check if it is ok now. Thanks

**Comment by PietroLiuzzo** [comment]
introduced error and now fixed

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Lb973e4b8ac54481db8890639c28be5cd
