### ISSUE TITLE
Herm. p. 62

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#139]
If you look for e.g. Herm. p. 62 in "Phrase Search", you will get every Herm. p. with every number.

**Comment by PietroLiuzzo** [comment]
#130

**Comment by PietroLiuzzo** [comment]
this shares the same cause as this #113 issue. apparently the analyzer ignores numbers

**Comment by AndreasEllwardt** [comment]
kannst Du das einbauen?



Zitat von Pietro Liuzzo <notifications@github.com>:
