### ISSUE TITLE
replace cases of I) instead of 1) if followed by 2)

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/dillmann#147]
from @AndreasEllwardt 
Ich stelle gerade fest, daß uns das OCR haufenweise statt 1 l in die Datei geschrieben hat. Das hätte ich beim Kontrollieren eigentlich merken sollen, in Times New Roman war das aber zu schwer für mich. Was also tun? Kann man irgendeine entsprechende Suche generieren? Insbesondere wären es Okkurenzen wie 1), wo also jetzt oft l) steht.

e.g. http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Ldd2148f521e442a0b1084e2d9e2ad848

**Comment by PietroLiuzzo** [comment]
I found 14 cases of sense[@n='I'] and none of these seams to have been wrongly matched from an original 1.

**Comment by wdickhut** [comment]
NB: not cases of I) instead of 1), but l) [i.e. L minuscola] instead of 1).

**Comment by PietroLiuzzo** [comment]
ahah! thanks! there are 24 of those which I am going to correct

**Comment by PietroLiuzzo** [comment]
fixed these.
