### ISSUE TITLE
second new meaning/sense 

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/dillmann#148]
When you open a second Sence Traces (or meaning), if you click the symbols from the string above (like "reference, bibliography, etc..") , the symbols  will be displayed  not within that meaning but  in the previous one. Again, after you write the second new meaning, when you go to save and edit it, you see that the new meaning appears written together with the previous meaning (in the same field).  See, e.g., the word ጽዮን (the second one). About it, I wanted to add a second traces meaning: I clicked "add more meaning" and I wrote inside. After I confimed it,  I saw that two maenings have been automatically merged in the same field and that, in the entry, the symbol <Sen< is wrongly displayed.

**Comment by vitagrazia81** [comment]
Sorry: "sense"

**Comment by PietroLiuzzo** [comment]
yes, this does not work. the point is that the two senses are ambiguous. they are both english and traces, whereas I expected, perhaps wrongly that a new sense would either have a new language or a different source. 
1. If there is a reason why this cannot be two meanings under the english traces meaning, then I will have to allow this case 
2. if it is ok as I believe that the two meanings for place an person name remain in one sense in english with source traces, then I will prevent the creation of a meaning already existing
let me know what I should do, but I am strongly inclined to act for 2.

**Comment by PietroLiuzzo** [comment]
I implemented solution 2 for the moment, which will prevent creation of a new english meaning if one already exists.

**Comment by vitagrazia81** [comment]
Yes, Pietro, for me the solution 2 is fine. I was thinking to write the second traces meaning in one sense as well, but then, I was somehow a bit confused from the possibilty to add a new sense again from Traces.

**Comment by vitagrazia81** [comment]
Pietro, now I have a problem with other entries. It does not allow me to add a new sense traces (the first) to the Dillmann sense. After clicking "Add More Meanings", when  I select the language english (en), it says that "a sense with this language already exists".

**Comment by PietroLiuzzo** [comment]
sorry for the inconvenience, this should be now fixed. Please close issue if ok
