### ISSUE TITLE
Wrong abbreviation in entry

### ISSUE THREAD

**Issue by SophiaD-M** [SChAth/dillmann#151]
I am not sure if this is the correct link, I hope so:
?mode=none&q=F.N.&id=Lc4ab02656dcc415f8d5903d2d4b9b6b3

Anyway, I was searching for references from the Feta Negest, F.N. While in the search results on the left screen the "F.N." was visible, it is not on the single entries when I click on them. In the single entry it says only "F.". And when I click on this F. it takes me to the Latin study tool, and not to the abbreviations list. 
That should be corrected! Thank you

**Comment by PietroLiuzzo** [comment]
this is an encoding problem which needs to be fixed by updating the data. in the example mentioned I fixed the unmarked citation to marked citations and the problem does not happen any more.

F.N. 5 needs to be marked as *F.N.|5*

**Comment by AndreasEllwardt** [comment]
item i.q. i.e. V.S.

**Comment by SophiaD-M** [comment]
ah, ok. Thank you. I understand only half of your explanation ;) But good to know that you are aware of the issue. 
Feta should of course also be spelled Fetha - my bad.

Another idea. There is a text edition of the F.N., should you have it in Beta Masaheft it would be a nice addition to the Dillmann app, if one could get access to the word in its textual context.

**Comment by PietroLiuzzo** [comment]
if you can get that file and permission to use I am happy to add it in!

**Comment by SophiaD-M** [comment]
Me? I don't work neither for B.M. nor for Dillmann! I am just making smart comments from the outside.

**Comment by PietroLiuzzo** [comment]
@AndreasEllwardt it is the same issue, check please, I have added now a quickfix.
@SophiaD-M if I do not know where it is or who has it, how am I supposed to get to it and add it to bm ? :) these minimal information would suffice, thanks!

**Comment by PietroLiuzzo** [comment]
@SophiaD-M the links in the attestion section, now highlight the word in the page where you land and if it is in a text they will take you to the exact section

**Comment by SophiaD-M** [comment]
Ignazio Guidi (ed., tr.), Il “Fetha Nagast” o “Legislazione dei Re” codice ecclesiastico e civile di Abissinia, Napoli 1897 (text), 1899 (tr.)   - most probably with expired copyright?
More modern:
Paulos Tzadua (ed., tr.), The Fetha Nagast. ፍትሐ ነገሥት. The Law of the Kings, Addis Ababa 1968 (Lit.)

**Comment by SophiaD-M** [comment]
Cool - thanks for changing it so quickly!

**Comment by PietroLiuzzo** [comment]
I am closing this issue as related to the visualization, the content mark up issue is well known and documented in other places.
