### ISSUE TITLE
Aktuelle Fassung der Prolegomena

### ISSUE THREAD

**Issue by wdickhut** [SChAth/dillmann#152]
Anbei eine aktualisierte Fassung der Prolegomena.
[Dillmann Lexicon Prolegomena 20170807.docx](https://github.com/SChAth/dillmann/files/1205275/Dillmann.Lexicon.Prolegomena.20170807.docx)

**Comment by PietroLiuzzo** [comment]
aktualisierte html http://betamasaheft.aai.uni-hamburg.de/Dillmann/DillmannProlegomena.html
