### ISSUE TITLE
Korrektur verschwunden!

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#166]
[Le71d73bd815f4e2e9bbcd689184e9799.pdf](https://github.com/SChAth/dillmann/files/1220040/Le71d73bd815f4e2e9bbcd689184e9799.pdf)

Zwei Mails vom 11. August 2017, 16:22:06 und 16:24:39 besagen, daß ich diesen Eintrag korrigiert habe. Diese Korrekturen sind weg.

Im Nachhinein wurde die Information distribuiert, daß man die App zu diesem Zeitpunkt besser nicht hätte benutzen sollen. Es wäre positiv, wenn derartige Verluste von Arbeitszeit künftig vermieden werden könnten. Innerhalb des Projektes sind ja bereits Erfahrungen mit schlecht funktionierender Software, die zu Datenverlusten führt, vorhanden.

**Comment by PietroLiuzzo** [comment]
you are right, those two corrections are gone. and only those two, being the only two edits which were done yesterday afternoon on a faulty version of the app, which I could not backup and therefore I substituted in the evening as per email. Be reassured that no change will be lost and this has been the unique case and happened for a known reason, namely the repair I had temporarily put in place was not ok. the current one is. and has preserved all changes done up to the first break down and after the last reinstall yesterday night. I have put back those changes. It does not look like there were other changes done in the afternoon yesterday.
