### ISSUE TITLE
Online DL Abbrev.: "Sal. Mar." = Salam ad Mariam I, II, III = which LIT references? 

### ISSUE THREAD

**Issue by fitawari** [SChAth/dillmann#19]
- printed DL lists 3 different abbreviations for works named "salutations to Mary" (Salam ad Mariam)

(1) Salam ad Mariam I = Cod. Bodl. XVIII fol. 47-62 = incipit ~ Engl.: "God gave the light who is threefold/tripled in the body/person" > what is the LIT reference for it? 
(2) Salam ad Mariam II = Cod. Bodl. XVIII fol. 62-63 = incipit ~ Engl.: "Salutation to you Covenant of Mercy, my hope, who renders justice to the sinner" > which LIT reference? 
https://archive.org/details/CatalogiCodicumManuscriptorumBibliothP7

(3) Salam ad Mariam III = Cod. Mus. Brit. LIII fol. 11-24 = incipit ~ Engl.: "Salutation to the commemoration of your pleasing name" > which LIT?  
https://opacplus.bsb-muenchen.de/metaopac/singleHit.do?methodToCall=showHit&curPos=1&identifier=100_SOLR_SERVER_1171941988 

when searching the BM database a "salam laki" query gives 62 results, but a "salam laki kidana" = zero results. Any help is welcome.

**Comment by thea-m** [comment]
(1) seems to be LIT3080RepCh360
(2) is LIT2806RepCh90
(3) you mean Cod. Mus. Brit. LXX? fol. 11-24 there is LIT2891RepCh172 (for this manuscript, there is already and entry in the database: BLadd16239)

For such hymns, https://www.zotero.org/groups/ethiostudies/items/itemKey/69U7EH56/q/chaine
is very useful: there are LIT entires for each hymn, and the pdf is searchable

**Comment by MassimoVilla** [comment]
(2) is LIT2812RepCh96. The incipit is ሰላም፡ ለኪ፡ ኪዳነ፡ ምሕረት፡ ተስፋየ፡ ዘታጸድቂ፡ ኃጥእ፡

**Comment by MassimoVilla** [comment]
1) should be LIT3082RepCh362 (so it is sorted in the abovementioned _Répertoire des salams_ by Marius Chaine with the label "O18" [= Oxford no. 18]). The incipit is እግዚአብሔር፡ ወሃቤ፡ ብርሃን፡ ዘይሤለስ፡ በአካሉ።, which is very similar to RepCh360 (i.e. እግዚአብሔር፡ አብ፡ ወሃቤ፡ ብርሃን፡ ዘይሤለስ፡ በአካሉ።).

**Comment by thea-m** [comment]
Massimo is right of course, I must have mixed something up

**Comment by fitawari** [comment]
Thanks a lot. I summarise: 
Sal. Mar. I = LIT3082RepCh362 
Sal. Mar. II = LIT2812RepCh96 
Sal. Mar. III = LIT2891RepCh172
