### ISSUE TITLE
online DL: representation/display of Coptic characters

### ISSUE THREAD

**Issue by fitawari** [SChAth/dillmann#22]
- Coptic characters are not displayed legibly, e.g.:  copt. ⲗⲓⲕ
- cp. entries here: http://betamasaheft.aai.uni-hamburg.de/Dillmann/search.html?q=Copt.

**Comment by PietroLiuzzo** [comment]
have you installed noto fonts?

**Comment by PietroLiuzzo** [comment]
how would you expect it to look like? could you paste here a correct example?

**Comment by fitawari** [comment]
I worked on the office computer yesterday, so the respective font is not on that one. 
Letters looked like "default boxes" only. 


      Von: Pietro Liuzzo <notifications@github.com>
 An: SChAth/dillmann <dillmann@noreply.github.com> 
CC: fitawari <fitawari@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 14:08 Donnerstag, 2.März 2017
 Betreff: Re: [SChAth/dillmann] online DL: representation/display of Coptic characters (#22)
   
how would you expect it to look like? could you paste here a correct example?—

**Comment by PietroLiuzzo** [comment]
I will install noto fonts on the machine, they are nicely visible to me here.
