### ISSUE TITLE
printed DL Sigla: "Fid. Jac. Bar." > to be added in online DL + assignment LIT reference no.?

### ISSUE THREAD

**Issue by fitawari** [SChAth/dillmann#30]
- in the printed DL list of Sigla there is "Fid. Jac. Bar.", but not in the abbrev. list of online DL; 
- corresponding LIT reference not searchable; 
- Hāymānotu lä-Yaʿqob ʾƎlbäradi “The Faith of Jacob Baradeus” (cp.: ESmakm004)

**Comment by thea-m** [comment]
The corresponding LIT record is LIT4010Haymanotu, which I found by the search
