### ISSUE TITLE
online DL Abbrev.: Sap. - two possible LIT references 

### ISSUE THREAD

**Issue by fitawari** [SChAth/dillmann#39]
- printed DL Sigla has: Sap. = "Sapientia Salomonis, apocr." = Wisdom of Solomon or Book of the Wisdom of Solomon 
- there are 2 possible LIT references: 
a) Ṭǝbaba Salomon - Wisdom of Solomon = LIT2516Wisdom 
b) Ṭǝbaba Salomon - Wisdom of Solomon = LIT2433tebaba 
- could you please merge or disambiguate these entries, please?

**Comment by thea-m** [comment]
Deleted LIT2433tebaba and changed all references, so you can use LIT2516Wisdom
