### ISSUE TITLE
Reihenfolge der Treffer

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#60]
Exakte Übereinstimmung sollte der erste Treffer sein: das klappt schon sehr gut, aber es gibt auch Fälle, wo zwei oder sogar drei Fälle von exakter Übereinstimmung vorliegen; das sollten dann die Treffer 1, 2, 3 sein.

**Comment by PietroLiuzzo** [comment]
Beispiele helfen... es ist jetzt geändert, so, bitte probiere nochmal. eine Ergebnisse in tei:form, also ዕለት in http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/L9a14aa1298674380b36629792eda9a99 haben einen score fünfmal multipliziert als normale Ergebnisse.
