### ISSUE TITLE
noch ein Wunsch

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#62]
Wenn ich eine Suchanfrage eintippe, aber das gewünschte Ergebnis nicht bekomme, möchte ich oftmals nur einen einzigen Buchstaben ändern, muß momentan aber alles neu eintippen. Geht das auch anders?

**Comment by PietroLiuzzo** [comment]
wenn du die erste buchstabe eintippt, bekommst du nichts vorschlage? etwas ist bestimmt falsch mit firefox... auch dorothea hat problemen damit die ich könnte nicht jetzt löschen.

**Comment by PietroLiuzzo** [comment]
jetzt die eingetippte Buchstabe bleiben da.
