### ISSUE TITLE
ein Pe ist kein Rho!

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#64]

**Comment by AndreasEllwardt** [comment]
Für U+0050 steht häufig 	U+03A1.

**Comment by PietroLiuzzo** [comment]
ich habe es oft in Ps. oder Prov. gefunden. hast du andere beispiele?

**Comment by PietroLiuzzo** [comment]
also, auch omicron statt lateinisch o findet man oft.

**Comment by PietroLiuzzo** [comment]
und epsilon statt lateinisch e

**Comment by PietroLiuzzo** [comment]
und A, B, H, I, M, N, T, X
