### ISSUE TITLE
order of the translations wrong

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#74]
በልዐ፡ I,1 [בָּלַע (ܒܠܰܥ) بَلْعَمَ بَلِعَ deglutivit, devoravit; amh. በላ፡] Subj. ይብላዕ፡ 1) edere,

die Reihenfolge auch hier falsch

**Comment by PietroLiuzzo** [comment]
und die richtige Reihenfolge wäre?
was bedeutet I,1 [...] ? was ist I ? was ist 1? was steht zwischen []?

**Comment by PietroLiuzzo** [comment]
#36
