### ISSUE TITLE
diacritics keyboard

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/dillmann#85]
add diacritics keyboard to textareas in edit and new forms. possibly with fidal as well

**Comment by PietroLiuzzo** [comment]
There is now a full feature keyboard on all input and textareas. Please test it. information on how to use it are available in the search help modal box, clicking the yellow i. it takes both combos and hold and choose. unfortunately it does not work properly for newly added meanings. workaround is to add meaning. save. edit again. then the keyboard will work there as well.
