### ISSUE TITLE
in message from update highlight somehow the exact changes made

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/dillmann#98]
store the original and compare with the new. is there a function to do this?

**Comment by PietroLiuzzo** [comment]
from @SusanneHummel

**Comment by eu-genia** [comment]
possibly also specify the latest `<change>` author in the message

**Comment by PietroLiuzzo** [comment]
The author of the notified modification has always been in the message, you probably haven't seen it.

quote:

There is something new in ጐጃም!

Vitagrazia said she/he: addition from Marrassini in this file

This is how it looks like in txt now:

Lbb2c7db04e1e4b20b1a3c5455846865b$ጐጃም$ , ጊጃም፡ n. provinciae Aeth. ጐዣም፡<i>gwažžām</i>; in 52:19 Chron. Am. 52.19

See ጐጃም online! There you can also update the file again.

**Comment by PietroLiuzzo** [comment]
two new features are provided. a jquery function compares the old and new txt file and reports with the positive confirmation message. in the email a table is provided listing the differences between the main areas of the entry. for use sense elements this might be equally not very useful but it is more useful than nothing
